name: "\U0001F41B Segnalazione di Bug"
description: Template per segnalare un bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: input
    id: description
    attributes:
      label: Descizione
      description: Chiara e concisa descrizione che identifica il bug
      placeholder: 
    validations:
      required: true
  - type: input
    id: company
    attributes:
      label: Azienda dove riprodurlo
      description: Codice azienda e relativa collocazione (nome server) su cui si verifica la problematica
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: download
    attributes:
      label: How did you download the software?
      options:
        - Homebrew
        - MacPorts
        - apt-get
        - Built from source
    validations:
      required: true
