name: "\U0001F41B Segnalazione di Bug"
description: Template per segnalare un bug
title: "[BUG]: "
labels: ["bug"]
body:
  - type: input
    id: description
    attributes:
      label: Descizione
      description: Chiara e concisa descrizione che identifica il bug
      placeholder: 
    validations:
      required: true
  - type: input
    id: company
    attributes:
      label: Azienda dove riprodurlo
      description: Codice azienda e relativa collocazione (nome server) su cui si verifica la problematica
      placeholder: 
    validations:
      required: true
  - type: checkboxes
    id: application
    attributes:
      label: Applicativo dove riprodurlo
      description: Dove si verifica la segnalazione?
      options:
        - label: SAM
          required: false
        - label: SAM Manager
          required: false
        - label: MES
          required: false
        - label: WMS
          required: false
        - label: RGT
          required: false
        - label: Web API
          required: false
        - label: JSON Import
          required: false
        - label: JSON Generator
          required: false
        - label: Portali
          required: false
  - type: textarea
    id: steps
    attributes:
      label: Per riprodurlo
      description: Passi per riprodurre il comportamento
      value: |
        1. Vai in '...'
        2. Clicca su '....'
        3. Spostati in '....' 
        4. Inserisci i valori '....'
        5. Visualizza l'errore
        ...
      render: markdown
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Comportamento aspettato
      description: "Chiara e concisa descrizione del comportamento aspettato"
      render: markdown
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Contenuti aggiuntivi
      description: "Eventuali informazioni aggiuntive relative al problema."
      render: markdown
    validations:
      required: true
