name: "\U0001F41B Segnalazione di Bug"
description: Template per segnalare un bug
title: "[BUG]: "
labels: ["bug"]
assignees:
  - 
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: description
    attributes:
      label: Descizione
      description: Chiara e concisa descrizione che identifica il bug
      placeholder: 
    validations:
      required: true
  - type: input
    id: company
    attributes:
      label: Azienda dove riprodurlo
      description: Codice azienda e relativa collocazione (nome server) su cui si verifica la problematica
      placeholder: 
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
    validations:
      required: true
  - type: dropdown
    id: application
    attributes:
      label: Applicativo dove riprodurlo
      multiple: true
      options:
        - SAM
        - SAM Manager
        - MES
        - WMS
        - RGT
        - Web API
        - JSON Import
        - JSON Generator
        - Portali
  - type: textarea
    id: steps
    attributes:
      label: Per riprodurlo
      description: Passi per riprodurre il comportamento
      value: " 1. Vai in '...'
        2. Clicca su '....'
        3. Spostati in '....'
        4. Inserisci i valori '....'
        5. Visualizza l'errore"
      placeholder:      
      validations:
        required: true
        
  - type: textarea
    attributes:
      label: Per riprodurlo
      description: Passi per riprodurre il comportamento
      value: |
          1. Vai in '...'
          2. Clicca su '....'
          3. Spostati in '....'
          4. Inserisci i valori '....'
          5. Visualizza l'errore"
      render: markdown        
- type: input
    id: expected
    attributes:
      label: Comportamento aspettato
      description: Chiara e concisa descrizione del comportamento aspettato
      placeholder: 
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Contenuti aggiuntivi
      description: Eventuali informazioni aggiuntive relative al problema.
