name: 💬 Nuova segnalazione
description: Template per inserire una nuova segnalazione
labels: ["triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## ❕ Non dimenticarti di assegnare la issue al team corretto
        Imposta nel campo _Assignees_ il team di competenza:
        * @team-core-csw
        * @team-afc-csw
        * @team-manufacturing-csw
        * @team-web-csw 
        # ✏ Inserimento dati
  - type: textarea
    id: descrizione
    attributes:
      label: Descrizione
      description: Chiara e concisa descrizione che identifica il comportamento riscontrato.
      placeholder: | 
        Non dimenticare di riportare in modo testuale eventuali messaggi mostrati dall'applicazione. 
        Questo consentirà di ricercarli in modo agevole in futuro.
    validations:
      required: true
  - type: input
    id: azienda
    attributes:
      label: Azienda dove riprodurlo
      description: Codice azienda e relativa collocazione (nome server) su cui si riproduce il comportamento riscontrato.
      placeholder: ex. "<NOME SERVER>.<NOME DATABASE>" oppure "<NOME CLIENTE> - <CODICE AZIENDA>"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Cliente
      description: Su quale cliente si è ricontrato il comportamento?
      options:    
        - Centro Software s.p.a.
        - Vittorio Ferri
        - Ecc...
  - type: dropdown
    id: version
    attributes:
      label: Versione
      description: Su quale versione di SAM si è ricontrato il comportamento?
      options:    
        - 6.8.0.35
        - 6.7.0.56
        - 6.6.0.5
        - 6.5.0.8
        - RC
        - DEVELOP        
        - 5.0
    validations:
      required: true
  - type: dropdown
    id: applicativo
    attributes:
      label: Applicativo dove riprodurlo
      multiple: true
      options:
        - SAM
        - MES
        - WMS
        - SAMSrv
        - SAMRep
        - SAMWebService
        - SAMJob
        - SAMService
        - JSONImport
        - JSONGenerator
        - Portali
        - Tools
        - BPM
  - type: textarea
    id: riprodurre
    attributes:
      label: Per riprodurlo
      description: Passi per riprodurre il comportamento
      placeholder: |
        1. Vai in  '...'
        2. Clicca su  '....'
        3. Spostati in '....'
        4. Inserisci i valori '....'
        5. ...
    validations:
      required: true
  - type: textarea
    id: aspettato
    attributes:
      label: Comportamento aspettato
      description: Descrizione chiara e concisa descrizione del comportamento aspettato.
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Se necessario aggiungere screenshots per aiutare ad esporre la casistica.
      placeholder: Puoi incollare direttamente le immagini, utilizzare il drag&drop o utilizzare i pulsanti dell'editor
  - type: textarea
    id: aggiuntivi
    attributes:
      label: Contenuti aggiuntivi
      description: Eventuali informazioni aggiuntive.
  - type: textarea
    id: watcher
    attributes:
      label: Per conoscenza
      description: Team menzionati per ricezione notifiche
      value: '@centrosoftware-dev/hd1'
